function [output, act_h, act_a] = Forward(W, b, X)
% [OUT, act_h, act_a] = Forward(W, b, X) performs forward propogation on the
% input data 'X' uisng the network defined by weights and biases 'W' and 'b'
% (as generated by InitializeNetwork(..)).
% This function should return the final softmax output layer activations in OUT,
% as well as the hidden layer pre activations in 'act_a', and the hidden layer post
% activations in 'act_h'.
layer_n = length(W);
act_a = cell(layer_n,1);
act_h = cell(layer_n,1);
curr_input = X;
sigmoid = @(x) 1/(1+exp(-x));
for i = 1 : length(W)
    curr_act = cell2mat(W(i))*curr_input+cell2mat(b(i));
    act_h(i) = num2cell(curr_act,1);
    curr_input = arrayfun(sigmoid, curr_act);
    act_a(i) = num2cell(curr_input,1);
end
softmax = @(x) exp(x);
act_a(end) = num2cell(arrayfun(softmax,curr_act),1);
act_a(end) = num2cell(cell2mat(act_a(end))/sum(cell2mat(act_a(end))),1);
output = act_a(end);
end
